version: "3"

services:
  auth:
    build: ./
    container_name: auth
    image:
      auth-image:latest
    expose:
      - 8000
    volumes:
      - /tmp/logs/auth:/app/logs
    env_file:
      - ./.env.example
    networks:
      - service_network


  db:
    image: postgres:13
    container_name: postgres
    expose:
      - 5432
    volumes:
      - auth_pg_data:/var/lib/postgresql/data/
    env_file:
      - .env.example
    networks:
      - service_network

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      - service_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - auth
    ports:
      - "8100:8100"
    networks:
      - service_network

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    container_name: jaeger
    expose:
      - 6831
    ports:
      - "16686:16686"
    networks:
      - service_network

  filebeat_nginx:
    image: elastic/filebeat:7.17.11
    container_name: filebeat_nginx
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./filebeat/filebeat_nginx.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - nginx
    networks:
      - service_network
      - elk_network

  filebeat_auth:
    image: elastic/filebeat:7.17.11
    container_name: filebeat_auth
    volumes:
      - /tmp/logs/auth/:/var/log/auth/:ro
      - ./filebeat/filebeat_app.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - service_network
      - elk_network

volumes:
  auth_pg_data:
    driver: local

networks:
  elk_network:
    name: elk_network
  service_network:
    name: service_network
