version: "3"

services:
  api:
    build: .
    ports:
      - "8000:5000"
    env_file:
      - .env
  db:
    image: postgres:13
    expose:
      - 5432
    volumes:
        - auth_pg_data:/var/lib/postgresql/data/
    env_file:
        - .env
  redis:
    image: redis
    expose:
      - 6379

volumes:
  auth_pg_data:
    driver: local
