version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev_configs:/etc/nginx/conf.d:ro
    network_mode: "host"

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "6831:6831/udp"
      - "16686:16686"
