"""init

Revision ID: ff6e2a83c57c
Revises: 
Create Date: 2023-10-02 01:29:46.206602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6e2a83c57c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('topic_message', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates')
    # ### end Alembic commands ###
