FROM python:3.10

WORKDIR /opt/app

COPY requirements.txt requirements.txt

RUN apt update \
    && apt install -y netcat \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

ENTRYPOINT ["/opt/app/load_data.sh"]
