version: "3"

services:

  elastic:
    image: elasticsearch:7.17.9
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - bd_network

  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - auth_pg_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ../auth/.env.example
    networks:
      - bd_network

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    networks:
      - bd_network


volumes:
  auth_pg_data:
    driver: local

  logstash_data:
    driver: local

networks:
  bd_network:
    name: bd_network
