version: "3"

services:

  filmworks_api:
    build: ../filmworks_api/.
    container_name: filmworks_api
    image:
      api-image:latest
    expose:
      - 8000
    volumes:
      - /tmp/logs/filmworks:/app/logs
    env_file:
      - ../filmworks_api/.env
    networks:
      - bd_network
      - servise_network

  ugc:
    build: ../ugc/.
    container_name: ugc
    image:
      ugc-image:latest
    expose:
      - 8001
    volumes:
      - /tmp/logs/ugs:/app/logs
    env_file:
      - ../ugc/.env.example
    networks:
      - bd_network
      - servise_network
      - kafka

  auth:
    build: ../auth/.
    container_name: auth
    image:
      auth-image:latest
    ports:
      - 8002:8002
    volumes:
      - /tmp/logs/auth:/app/logs
    env_file:
      - ../auth/.env.example
    networks:
      - bd_network
      - servise_network


networks:
  bd_network:
    name: bd_network

  servise_network:
    name: servise_network

  kafka:
    name: kafka
