version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app

  ugc:
    build: ../ugc/.
    container_name: ugc
    image:
      ugc-image:latest
    expose:
      - 8000
    volumes:
      - /tmp/logs/ugs:/app/logs
    env_file:
      - .env.example
    networks:
      - mongo
      - app

  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - ugc

  filebeat_nginx:
    image: elastic/filebeat:7.17.11
    container_name: filebeat_nginx
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./filebeat/filebeat_nginx.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - nginx
    networks:
      - app
      - elk_network

  filebeat_ugc:
    image: elastic/filebeat:7.17.11
    container_name: filebeat_ugc
    volumes:
      - /tmp/logs/ugs/:/var/log/ugc/:ro
      - ./filebeat/filebeat_app.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - app
      - elk_network


networks:
  app:
    name: app
  mongo:
    name: mongo
    external: True
  elk_network:
    name: elk_network
    external: True
  # clickhouse:
  #   name: clickhouse
  #   external: True
  # kafka:
  #   name: kafka
  #   external: True
