version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app

  ugc:
    build: .
    env_file:
      - .env
    networks:
      - kafka
      - clickhouse
      - mongo
      - app
    ports:
      - "8100:8000"
    expose:
      - 8000

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - ugc
    networks:
      - app
    ports:
      - "8300:8200"

networks:
  app:
    name: app
  clickhouse:
    name: clickhouse
  kafka:
    name: kafka
    external: True
  mongo:
    name: mongo
    external: True
