version: "2.2"

volumes:
  dev-postgres_data:
    driver: local

services:

  es01:
    image: elasticsearch:7.17.9
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 5s
      timeout: 10s
      retries: 120

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
        - dev-postgres_data:/var/lib/postgresql/data/
        - ./utils/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
